### ISSUE TITLE
build for Windows

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/cuda-miner#14]

**Comment by rsmmnt** [comment]
for now windows compilation gives errors cause of preprocessing in inline asm, workaround is to hardcode hex values in asm in mining.cu and prehash.cu, so windows version is coming soon

**Comment by rsmmnt** [comment]
https://github.com/rsmmnt/Autolykos-GPU-miner/blob/win64/secp256k1/gpuminer.exe

very raw and untested win64 build, may not work, I don't have win machine with 3GB+ card to test

**Comment by catena2w** [comment]
see https://ergoplatform.org/blog/2019_05_07_mining/
