### ISSUE TITLE
Not compiled on CUDA 10.1

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/cuda-miner#15]
Hi!

Seems miner not compile on CUDA 10.1:

```
root@ubuntu:~/workspace/miners/Autolykos-GPU-miner/secp256k1# make
rm -f ./src/request.o ./src/compaction.o ./src/mining.o ./src/cryptography.o ./src/conversion.o ./src/processing.o ./src/prehash.o ./src/definitions.o ./src/reduction.o ./src/jsmn.o ./src/autolykos.o ./lib/lib.a test.out auto.out
nvcc -O3 -c -gencode arch=compute_75,code=sm_75 -arch=sm_30 -gencode arch=compute_75,code=compute_75 src/request.cu -o src/request.o
src/request.cu(39): warning: a user-provided literal suffix must begin with "_"

src/request.cu(39): error: user-defined literal operator not found

src/request.cu(41): error: user-defined literal operator not found

2 errors detected in the compilation of "/tmp/tmpxft_000034cb_00000000-7_request.compute_75.cpp1.ii".
Makefile:31: recipe for target 'src/request.o' failed
make: *** [src/request.o] Error 1
```

I have latest nvidia-driver-418 and latest cuda-10.1 installed. Ubuntu 18.04.2

**Comment by rsmmnt** [comment]
that's a C++ standard problem, these files compile OK with old C++98 standard, with C++11 these errors come out, probably cuda 10.1 uses c++11 by default

need to specify c++ version explicitly in makefile, try adding --std=c++98 to CFLAGS

**Comment by ponte83** [comment]
preface: i'm not sure what i'm doing...

i tried specify CFLAGS = -c --std=c++98 in makefile and it says:

**nvcc fatal   : Value 'c++98' is not defined for option 'std'
Makefile:31: recipe for target 'src/request.o' failed
make: *** [src/request.o] Error 1**

as i can see in nvcc documentation (https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#nvcc-command-options) there are only these specified option for --std 

**Allowed Values
    c++03
    c++11
    c++14**

than i tried to use c++03 and the error is:

**src/cryptography.cu(177): error: incomplete type is not allowed**

**src/cryptography.cu(181): error: identifier "BN_init" is undefined**

**2 errors detected in the compilation of** **"/tmp/tmpxft_0000224f_00000000-7_cryptography.compute_75.cpp1.ii".**
**Makefile:31: recipe for target 'src/cryptography.o' failed**
**make: *** [src/cryptography.o] Error 1**

**Comment by rsmmnt** [comment]
yes,  --std=c++03, sorry

and these errors - another thing that needs little fixing - miner currently does not work with openssl 1.1.x, but works ok with openssl 1.0.2 for example

**Comment by andyceo** [comment]
So, WORKAROUND is here :)

1. sudo apt install libcurl3
2. sudo apt install libcurl-openssl1.0-dev
3. sudo apt install libssl1.0-dev
4. In Makefile:

        -CFLAGS = -c
        +CFLAGS = -c --std=c++03
4. make

Miner compiles with several minor warnings:

```
$ make
rm -f ./src/request.o ./src/compaction.o ./src/mining.o ./src/reduction.o ./src/cryptography.o ./src/conversion.o ./src/processing.o ./src/prehash.o ./src/definitions.o ./src/jsmn.o ./src/autolykos.o ./lib/lib.a test.out auto.out
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/request.cu -o src/request.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/compaction.cu -o src/compaction.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/mining.cu -o src/mining.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/reduction.cu -o src/reduction.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/cryptography.cu -o src/cryptography.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/conversion.cu -o src/conversion.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/processing.cu -o src/processing.o
src/processing.cu: In function ‘char* TimeStamp(timestamp_t*)’:
src/processing.cu:43:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
     sprintf(stamp->timestamp + 24, "%03d: ", millisec);
                                                    ^
src/processing.cu: In function ‘int PrintPuzzleState(const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, const uint8_t*, timestamp_t*)’:
src/processing.cu:190:2258: warning: format ‘%lX’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘int’ [-Wformat=]
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/prehash.cu -o src/prehash.o
nvcc -O3 -c --std=c++03 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 src/definitions.cu -o src/definitions.o
nvcc -O3 -c --std=c++03 src/jsmn.c -o src/jsmn.o
mkdir -p ./lib;
ar rc ./lib/lib.a ./src/request.o ./src/compaction.o ./src/mining.o ./src/reduction.o ./src/cryptography.o ./src/conversion.o ./src/processing.o ./src/prehash.o ./src/definitions.o ./src/jsmn.o
ranlib ./lib/lib.a
nvcc ./src/autolykos.cu ./lib/lib.a -L/usr/local/lib -lcurl -I/usr/local/include -lssl -lcrypto -O3 -gencode arch=compute_70,code=sm_70 -arch=sm_30 -gencode arch=compute_70,code=compute_70 \
-o auto.out
./src/autolykos.cu: In function ‘int main(int, char**)’:
./src/autolykos.cu:137:2468: warning: format ‘%lX’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘int’ [-Wformat=]
```

Note that I had to downgrade target platform to `compute_70` since I have CUDA 9 and old GPU (see https://github.com/ergoplatform/Autolykos-GPU-miner/issues/17).

Also note that installing outdated curl headers leads to removing many packages:

```
$ sudo apt install libcurl3
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Следующие пакеты устанавливались автоматически и больше не требуются:
  antlr bsdtar bwidget db-util db5.3-util docbook-xml docbook-xsl extlinux fop hfsplus icoutils javahelp2 ldmtool libantlr-java libarchive-tools libbfio1 libboost-log1.65.1 libboost-program-options1.65.1 libconfig9 libdate-manip-perl libecj-java libewf2 libflexdock-java
  libfop-java libfreehep-graphicsio-emf-java libgluegen2-jni libgluegen2-rt-java libhfsp0 libhivex0 libintl-perl libintl-xs-perl libjeuclid-core-java libjgoodies-looks-java libjgraphx-java libjlatexmath-fop-java libjlatexmath-java libjogl2-java libjogl2-jni libjrosetta-java
  liblaf-plugin-java libldm-1.0-0 libleatherman-data liblucene4.10-java libmatio4 libregexp-java libsaxon-java libskinlf-java libssl-doc libstring-shellquote-perl libsys-virt-perl libtcl8.5 libtk8.5 libwin-hivex-perl lsscsi ruby-blankslate ruby-builder ruby-childprocess
  ruby-erubis ruby-excon ruby-fog-core ruby-fog-json ruby-fog-libvirt ruby-fog-xml ruby-formatador ruby-i18n ruby-json ruby-libvirt ruby-log4r ruby-multi-json ruby-net-scp ruby-oj scilab-data scilab-include scrub sgml-data supermin tcl8.5 tk8.5 zerofree
Для их удаления используйте «sudo apt autoremove».
Следующие пакеты будут УДАЛЕНЫ:
  curl facter libafflib0v5 libcpp-hocon0.1.6 libcurl4 libfacter3.10.0 libguestfs-hfsplus libguestfs-perl libguestfs-reiserfs libguestfs-tools libguestfs-xfs libguestfs0 libleatherman1.4.0 libtsk13 php-curl php7.2-curl scilab scilab-cli scilab-full-bin scilab-minimal-bin
  scilab-sivp sleuthkit steam-launcher vagrant vagrant-libvirt
Следующие НОВЫЕ пакеты будут установлены:
  libcurl3
Обновлено 0 пакетов, установлено 1 новых пакетов, для удаления отмечено 25 пакетов, и 185 пакетов не обновлено.
Необходимо скачать 214 kB архивов.
После данной операции объём занятого дискового пространства уменьшится на 90,0 MB.
```

Sorry for non-english messages but I think everything is clear.

**Comment by ponte83** [comment]
hi again!
it compiled with CFLAGS = -c --std=c++03 with some warnings into auto.out BUT it didn't produced any config.json:

```
ub@ub:~/Autolykos-GPU-miner/secp256k1$ ./auto.out 
Thu 04/18/2019 09:19:08:252:  Checking GPU availability
Using configuration from './config.json'
ABORT:  File './config.json' not found
Thu 04/18/2019 09:19:08:266:  Miner is now terminated
```

i have to say that this is the **second time i run make**, first time i had an error (but the config.json was produced) so i removed all /Autolykos-GPU-miner folder, cloned again and compiled.

i manually added the config.json and ./auto.out response:
```
Thu 04/18/2019 09:21:06:965:  Checking GPU availability
Using configuration from './config.json'
Thu 04/18/2019 09:21:06:980:  Generated public key:
   pk = 0x03 94C587F8527F1177 C5EC7145CE5720CD 5B3DC847392D1A3C 527F34809111184D
Thu 04/18/2019 09:21:06:980:  Allocating GPU memory
ERROR:  CUDA failed at ./src/autolykos.cu: 174
Miner is now terminated
```
is that my old video card doesn't have enough memory (2gb)?

// precalculated hashes
           // N_LEN * NUM_SIZE_8 bytes // 2 GiB
           uint32_t * hashes_d;
**174**    CUDA_CALL(cudaMalloc((void **)&hashes_d, (uint32_t)N_LEN * NUM_SIZE_8));

**Comment by rsmmnt** [comment]
Yes, currently without prehash:true option it needs at least 3GB card.
From nvidia-smi - 
 `  0     18197      C   ./auto.out                                  2831MiB`

**Comment by ponte83** [comment]
same with prehash:false
i mean even if i specify prehash:false in the **manually added** config.json ...
could be that the first time i compiled (and it generated the config.json file) it was kind stored somewhere and when i call the auto.out it refers to that previously generated config file that now i can't find?
probably this is a stupid guess...

**Comment by sumvorax** [comment]
I agree it is not the most convenient way of doing that:
I originally presumed, that config.json is to be created by user manually
(from stub.json by renaming and adding correct seed).
so not, now make is not generating any config file.
Probably it should be changed.

**Comment by andyceo** [comment]
I can prove that latest (for now) commit  `7a89253b` is compiles and works on Ubuntu 18.04.2, Cuda 10.1 and nvidia-driver-418 with only curl library replacement, so do: `sudo apt install libcurl3 libcurl-openssl1.0-dev libssl1.0-dev` and `make`, then create your own `config.json` and run with `./auto.out config.json`.

Great work, guys!

**Comment by andyceo** [comment]
This bug was fixed very long time ago. Now it is compiles ok according README.md manual.
