### ISSUE TITLE
Miner too fragile for user input

### ISSUE THREAD

**Issue by andyceo** [ergoplatform/cuda-miner#18]
Currently, miner stops if user press any button. This is happens very often, especially by users that get used to check if program (or computer) not hanged by pressing space button and see that terminal print it back, and that usually does not break program. 

Think would be much better to cancel only on Ctrl+C like most programs do.

**Comment by sumvorax** [comment]
I changed exit condition for foreground mode. Now only 'q' / 'Q' of ordinary keys aborts the miner.
