### ISSUE TITLE
Prehash CUDA error

### ISSUE THREAD

**Issue by rsmmnt** [ergoplatform/cuda-miner#34]
There is an error that occurs from time to time:

2019-05-03 08:02:12,234 INFO [GPU 0 miner] GPU 0 read new block data
ERROR:  CUDA failed at src/prehash.cu: 1019
Miner is now terminated

It's at cudaMemcpy call and seems like it tries to read from wrong chunk of memory

```
   CUDA_CALL(cudaMemcpy(
        (void *)&len, (void *)(invalid + 2 * N_LEN), INDEX_SIZE_8,
        cudaMemcpyDeviceToHost
    ));
```

so probably kernels before that call can yield corrupted value of `invalid`

**Comment by catena2w** [comment]
fixed by https://github.com/ergoplatform/Autolykos-GPU-miner/pull/38
