### ISSUE TITLE
Low performance of a miner

### ISSUE THREAD

**Issue by travek** [ergoplatform/cuda-miner#53]
Hello!
I started mining on Ergo mainnet. I noticed that the performance of a miner is very low or there's somethig wrong in the miner. And the arguments are
1) Hashrate is floating. It may be (in my case) around 13 then may drop to 0.8, then can rise to 2 and so on.
2) Today my hashrate is more constant and is around 12 MH/s. Curling time is between 7 and 11 sec.
3) Performance monitor shows that GPU is utilization is low. GPU RAM is utilized less than 50 %. (I'm using gtx 1060).
4) I did mining several hours today and yesterday and my mining reward=0. That seems also strange to me as I see very fee peers in the network and some reward is expected to be allocated for my node.

What logs are needed to analyse low mining performance ?

**Comment by rsmmnt** [comment]
You have gtx1060 with < 8gb ram.
First day of mining the block interval was around 10-20s, it's impossible to mine anything with keepPrehash: false, cause first 30 secs after getting new candidate miner calculates hashes without grinding nonces...
It is floating because of that.
Look up hashrate at explorer.ergoplatform.com, it's > 1Th/s.

**Comment by travek** [comment]
Thanks for the hint.
What block inteval is realistic for the option "keepPrehash: false" to be competetive with miners having >=8Gb ?

**Comment by rsmmnt** [comment]
Average block interval should be 2 min, and it's now about that.
So you get average 1.5 min of mining now with each block with <8GB cards.

**Comment by travek** [comment]
Thanks!
Closing the issue

**Comment by travek** [comment]
I'm mining now.
I have 6Gb RAM.
Hashrate is around 12 MH. But RAM utilization is around 40%, not more, GPU utilization is super low. CPU and all other resources are not used.
Why hashrate is low and keeps stable ?

**Comment by rsmmnt** [comment]
If you don't have 8GB ram, it uses ~2-3Gb.
Mining algorithm is memory-hard, not compute-hard, it makes a lot of uncorrelated memory accesses.
Your hashrate is adequate, as it seems to me.
How do you measure GPU utilization? 
nvidia-smi should say that GPU-util is ~ 100%.

**Comment by travek** [comment]
I looked into Win task monitor.
Thanks
